apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-python-app
spec:
  rules:
  - host: "my-python-app.test.com"
    http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: my-python-app
              port:
                number: 8080
